### ISSUE TITLE
Optimize instance requests and contacts

### ISSUE THREAD

**Issue by nitot** [cozy/cozy-docs#101]
We need to improve the process for requesting instances. Here are a few changes I would like to see: 

## At the top of the page: 

1 - Insert a "About" link that leads to the About section (may need to add an "about" id there)
2 - Insert a "Contact" link also that takes the visitor to the "Get in touch" section http://cozy.io/fr/#contact

## Further down:

3 - Insert a "instance-request" id next to the "I want to contribute form" so that we can send people to http://cozy.io/fr/#instance-request by email
4 - replace "you can also write directly to contact@cozycloud.cc if you prefer" by "Need to contact the team for other reasons ? Just use this trusty and decentralized tool called email by sending a message to contact@cozycloud.cc"

**Comment by frankrousseau** [comment]
Another thing, we should remove the ask for an instance via email in the install section (Hosting Services paragraph).

**Comment by nitot** [comment]
@frankrousseau : that's pretty much what the item #4 tries to do.

**Comment by frankrousseau** [comment]
Ok.

**Comment by m4dz** [comment]
All right, I'll do it tonight ;)

**Comment by frankrousseau** [comment]
@m4dz did you handle it?

**Comment by m4dz** [comment]
Yep, I'm on it :)
