### ISSUE TITLE
Mobile application requires 'files' installation on cozy

### ISSUE THREAD

**Issue by poupotte** [cozy/cozy-docs#102]

**Comment by frankrousseau** [comment]
We can add it to the documentation. But warning messages should be included in the documentation.

**Comment by poupotte** [comment]
When device will be declared as application, it'll be able to defined its own _design document on files, then this requirement will be optionnal. 
Before this change, we can improve documentation (3c53490) and improve warning in mobile application.

**Comment by poupotte** [comment]
This issue is not relevant anymore. Mobile works without cozy-files.
