### ISSUE TITLE
Adding to sources.list.d requires you run as *root* (not just sudo)

### ISSUE THREAD

**Issue by terrycloth** [cozy/cozy-docs#146]
I'm reading the [installation instructions for Ubuntu](http://cozy.io/en/host/install/install-on-ubuntu.html).

I'm testing on a Ubuntu 14.04.2 virtual machine (running in GNOME Boxes on my Ubuntu 15.04 64-bit desktop).

When I get to this command...

```
sudo echo 'deb https://ubuntu.cozycloud.cc/debian trusty main' \
 > /etc/apt/sources.list.d/cozy.list
```

...when I try this, it says "Permission denied." I'm only able to add the source if I manually run `sudo vim` and paste the string into the `cozy.list` file, or if I run the `echo` command *after* changing to the root user with `sudo su`.

Does this happen for you too? If this is reproducible, let's correct it. If it only happens for me, though, this permissions issue confuses me.

**Comment by frankrousseau** [comment]
@Kloadut any idea about making this command proper?

**Comment by nicofrand** [comment]
```console
echo 'deb https://ubuntu.cozycloud.cc/debian trusty main' | sudo tee /etc/apt/sources.list.d/cozy.list > /dev/null
```
should work !
