### ISSUE TITLE
Missing curly brackets in code snippet in "Discover Americano" page.

### ISSUE THREAD

**Issue by terrycloth** [cozy/cozy-docs#155]
I'm reading [`src/documents/en/hack/getting-started/discover-americano.html.md`](https://github.com/cozy/cozy-docs/blob/master/src/documents/en/hack/getting-started/discover-americano.html.md).

Under the "Define the models" heading (starting at line 79), I see this code snippet:

```javascript
module.exports =
  bookmark: {
    all: function(doc) {
      emit(doc._id, doc);
    }
  };
```

This doesn't appear valid. I believe this should have another set of curly brackets wrapped around `bookmark`, like this.

``` javascript
module.exports = {
  bookmark: {
    all: function(doc) {
      emit(doc._id, doc);
    }
  }
};
```

Unless you meant something else...?

**Comment by clochix** [comment]
Thanks @terrycloth, you're definitively right ! I just pushed a fix, pinging @frankrousseau for merging ;-)

**Comment by clochix** [comment]
The fix has been published, closing this, thanks again @terrycloth
