### ISSUE TITLE
Document how to send emails from self hosted instances

### ISSUE THREAD

**Issue by clochix** [cozy/cozy-docs#168]
Here's the draft of this documentation : 
https://mensuel.framapad.org/p/cozypostfix

Once the documentation is online, please open a ticket on home screen to link this documentation from parameters screen, on self-hosted instances.

**Comment by nono** [comment]
@clochix with https://github.com/clochix/cozy-docs/commit/75300eb5fc5b812c6dc55d4f10b1cbfb080f3a50, can we close this issue?
