### ISSUE TITLE
2 (possible) typos

### ISSUE THREAD

**Issue by 3onyc** [cozy/cozy-docs#197]
**In `src/documents/en/hack/getting-started/architecture-overview.html.md`**

* `tranverse`, not an English word, not sure what it should be

**In `src/documents/en/hack/cookbooks/data-system.html.md`**

* `recuce`, should probably be reduce

**Comment by clochix** [comment]
Thanks for reporting @3onyc :-)
@lemelon would you mind having a look at this ? Thanx !

**Comment by clochix** [comment]
Sorry, this has been fixed for some time now, but we forgot to give you an update.
Thanks again for reporting ☺
