### ISSUE TITLE
Problème de redirection systématique vers la doc en anglais

### ISSUE THREAD

**Issue by LaPalice** [cozy/cozy-docs#237]
Depuis l'adresse https://docs.cozy.io/fr/, cliquer sur Installation, Synchronisation du mobile ou Développement d'application redirige vers la doc en anglais et non vers celle en français.

**Comment by clochix** [comment]
Pour information, la documentation sur le développement d'application n'est disponible qu'en anglais, je viens donc de refaire pointer le lien vers les mages anglaises (il conduisait à une 404 suite au précédent commit).

Merci du signalement @LaPalice ☺
