### ISSUE TITLE
VirtualBox 5 not supported by Vagrant ?

### ISSUE THREAD

**Issue by Jolg42** [cozy/cozy-docs#246]
Hi, 

I wanted to try cozy after the new (awesome) docs published

But I have this problem, of course I'm gonna install Virtualbox 4, but it's just annoying, do you know how to do something else or we just have to wait ?

```
info - cozy-dev    | Starting the virtual machine...this may take a while.
The provider 'virtualbox' that was requested to back the machine
'default' is reporting that it isn't usable on this system. The
reason is shown below:

Vagrant has detected that you have a version of VirtualBox installed
that is not supported. Please install one of the supported versions
listed below to use Vagrant:

4.0, 4.1, 4.2, 4.3
error - cozy-dev    | An error occurred while your VMs was starting.
```

**Comment by Jolg42** [comment]
My bad, sorry for the issue.

My Vagrant version was 1.7.2, after updating to 1.8.1, everything is now working!

`info - cozy-dev    | The virtual machine has been successfully started.`

**Comment by frankrousseau** [comment]
Great! Feel free to ask any questions about the dev environment. Try IRC too for quicker answers: irc.freenode.net #cozycloud
