### ISSUE TITLE
Explain how to import a self-signed certificate

### ISSUE THREAD

**Issue by clochix** [cozy/cozy-docs#247]
Until now, we linked to an external documentation to explain how to import a self-signed certificate. This page is gone, so we need to add the tutorial into our own documentation.
We could use the [archive](https://web.archive.org/web/20140712044746/http://davdroid.bitfire.at/faq/entry/importing-a-certificate) of the page or [this tutorial](http://wiki.cacert.org/FAQ/ImportRootCert#Android_Phones_.26_Tablets).

**Comment by clochix** [comment]
@kosssi or @poupotte, would you mind having a look at this please? I don't have an Android device, so am probably not the best person to write this doc.

**Comment by poupotte** [comment]
This issue is now fixed : https://docs.cozy.io/en/mobile/trouble.html
