### ISSUE TITLE
step by step doc : admin creation in couchdb does not work

### ISSUE THREAD

**Issue by nsteinmetz** [cozy/cozy-docs#265]
Hi,

I have this as result:

```
curl -s -X PUT 127.0.0.1:5984/_config/admins/$(head -n1 /etc/cozy/couchdb.login) -d "\"$(tail -n1 /etc/cozy/couchdb.login)\""
{"error":"error","reason":"eacces"}
```

Thanks,
Nicolas

**Comment by clochix** [comment]
Hi @nsteinmetz,

`eaccess` often means there's an access right problem.
Could you have a look at CouchDB's logs (`/var/log/couchdb/couch.log`) and and look for error messages trying to access some file?

**Comment by nsteinmetz** [comment]
Looks it was an issue with permissions on files.

Re-applying:

```
chown -R couchdb:couchdb /usr/local/{lib,etc}/couchdb /usr/local/var/{lib,log,run}/couchdb
service couchdb restart
```

And it works :)
