### ISSUE TITLE
ReferenceError: jQuery is not defined

### ISSUE THREAD

**Issue by clochix** [cozy/cozy-docs#319]
I get this error message in the JS console of my browser each time I navigate inside the site using the top menu. See https://github.com/cozy/cozy-docs/blob/master/src/documents/assets/javascripts/main.js.coffee#L1

jQuery doesn't seem to be loaded at the time the `main.js` script is executed.

**Comment by jsilvestre** [comment]
Does this have any impact on the user experience?

**Comment by clochix** [comment]
Menu seems to work, so I don't know if this break some feature.

**Comment by jsilvestre** [comment]
Thank you, I didn't take the time to check by myself. Let's say nothing needs to be fixed then, I close and mark it as wontfix. Feel free to reopen if the UX is broken, of course!
