### ISSUE TITLE
Mobile sync screencasts are outdated

### ISSUE THREAD

**Issue by clochix** [cozy/cozy-docs#333]
Screencasts showing how to “prepare your Cozy” before sync use an old version of the home, so they are very confusing for users.
https://docs.cozy.io/en/mobile/calendar.html
https://docs.cozy.io/en/mobile/contacts.html

**Comment by sblaisot** [comment]
@clochix links no longer available. issue to be closed ?

**Comment by clochix** [comment]
Yes, you're right.
Thanks!
