### ISSUE TITLE
Rename cozy-manager to cozy-dev in documentation

### ISSUE THREAD

**Issue by clochix** [cozy/cozy-docs#45]
See my comments on https://github.com/cozy/cozy-docs/commit/5148edb05690e39d0acb7b0e45f9b510afcfa7ca#commitcomment-8498702

**Comment by frankrousseau** [comment]
Fixed in https://github.com/cozy/cozy-docs/commit/ba696b01af63588ed51eef4487a516a944997236. Thank you for reporting.
