### ISSUE TITLE
Broken link in french install doc

### ISSUE THREAD

**Issue by NumEricR** [cozy/cozy-docs#93]
Hi,

There is a broken link in src/documents/fr/host/install.html.md: see "[description de l’architecture](https://github.com/cozy/cozy-docs/blob/master/src/documents/fr/host/install.html.md#quest-ce-que-le-script-va-installer-sur-votre-serveur)".
The generated URL is "https://cozy.io/fr/hack/getting-started/architecture-overview.html" but there is no "hack" directory in the "fr" one.

Maybe this link should use the URL "https://cozy.io/en/hack/getting-started/architecture-overview.html" with "(en anglais)".

**Comment by clochix** [comment]
Thanks for reporting @NumEricR. For now, we haven't translated the "hack" section of the documentation, so you're right, we should probably link to the English document.
@jsilvestre, what do you think ?

**Comment by jsilvestre** [comment]
You are absolutely right. Sorry for that, the localization thing has been done in 2 days with automatic scripts, resulting in that kind of errors. I'm going to go through all the documentation to fix it.

**Comment by jsilvestre** [comment]
Ce sera corrigé après que ce code ait été accepté : https://github.com/cozy/cozy-docs/pull/97

**Comment by NumEricR** [comment]
I close this issue since #97 has been merged.

**Comment by frankrousseau** [comment]
Thank you @NumEricR !
