### ISSUE TITLE
Clarify the use of Nginx

### ISSUE THREAD

**Issue by clochix** [cozy/cozy-docs#95]
Some users installing Cozy are not aware that it need Nginx. We should make it clearer in the doc, and also provide sample configuration of Apache vhosts, for user already running a Web server.

cc @franck-paul

**Comment by clochix** [comment]
Thanks to @franck-paul, here's some documentation for Apache https://forum.cozy.io/t/installation-manuelle-erreur-config-nginx/313/4 and http://open-time.net/post/2015/03/12/Cozy-avec-Apache

**Comment by nono** [comment]
@clochix do you think we can close this issue?

**Comment by clochix** [comment]
Yes, we haven't had questions on Nginx for quite a while, so I think we can close this one.
